name: Publish Docker image on merge

on:
  pull_request:
    types: [closed]
    branches:
      - develop
      - main

jobs:
  publish:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: >-
      github.event.pull_request.merged == true &&
      github.event.pull_request.head.repo.full_name == github.repository

    steps:
      - name: Debug event
        run: |
          echo "Merged: ${{ github.event.pull_request.merged }}"
          echo "Base ref: ${{ github.event.pull_request.base.ref }}"
          echo "Repo: ${{ github.event.pull_request.head.repo.full_name }}"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e Push - Develop
        if: github.event.pull_request.base.ref == 'develop'
        run: |
          docker build \
            --build-arg ENV_FILE="${{ secrets.ENV_FILE_DEVELOP }}" \
            -t rodrigoapolo/front-rick:develop-latest \
            -t rodrigoapolo/front-rick:develop-${{ github.sha }} \
            .
          docker push rodrigoapolo/front-rick:develop-latest
          docker push rodrigoapolo/front-rick:develop-${{ github.sha }}

      - name: Build e Push - Main
        if: github.event.pull_request.base.ref == 'main'
        run: |
          docker build \
            --build-arg ENV_FILE="${{ secrets.ENV_FILE_PRODUCTION }}" \
            -t rodrigoapolo/front-rick:main-latest \
            -t rodrigoapolo/front-rick:main-${{ github.sha }} \
            .
          docker push rodrigoapolo/front-rick:main-latest
          docker push rodrigoapolo/front-rick:main-${{ github.sha }}
